### ISSUE TITLE
ログイン・ログアウト

### ISSUE THREAD

**Issue by kensei18** [kensei18/collaborative_project#14]

**Comment by nanako0707** [comment]
@kensei18 
#13 このイシュー対応時にログイン・ログアウトできていたので、
こちらはクローズでも大丈夫でしょうか？？

![1558FBEF-9F7D-4F88-BB85-8B2013530872](https://user-images.githubusercontent.com/61221142/148501342-890dc908-a65d-458f-b80c-e0d9f1ae02d4.jpeg)
![48B9E5CA-5BDA-4B2B-94C2-B922ADA10D1C](https://user-images.githubusercontent.com/61221142/148501346-7c5ee63d-0b66-418d-be8a-0d0d3b5856a8.jpeg)

**Comment by kensei18** [comment]
@nanako0707 

あー、そうかもな、と思ってました笑
ちなみにログインした時にトークンってどうやって渡されますか？？

**Comment by nanako0707** [comment]
https://blog.nightonly.com/2021/08/14/devise-token-auth%E3%81%AE%E6%8C%99%E5%8B%95%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%97%E3%81%A6%E3%81%BF%E3%81%9F/

ログインしたら access-token は暗号化してDBに保存しておいて、それを使う感じになりますかね・・？？
