### ISSUE TITLE
お気に入り追加

### ISSUE THREAD

**Issue by kensei18** [kensei18/collaborative_project#15]
- [x] テーブル構成：favorite columns → reference: user, feed
- [x] ログイン中のユーザのみ、お気に入り登録できる。

**Comment by kensei18** [comment]
カラム案

- reference: user, feed

だけ！

**Comment by nanako0707** [comment]
お気に入り追加機能を実装しました！

![27DD4736-13D5-4149-B783-43B163A790CD](https://user-images.githubusercontent.com/61221142/148883383-80f5a3f4-487c-4585-bfa2-33508e1fbb61.jpeg)

引き続き削除機能を追加致します🙇‍♀️
